### PR TITLE
Add SpannableStringBuilder#scale

### PR DESCRIPTION
**Pull request by mightyfrog**
Add RelativeSizeSpan wrapper.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is this common? We tried to include only the common ones as `inSpans` is always available for use with _any_ span.

**Comment by mightyfrog** [comment]
I use it where bold doesn't have any effect, like some Japanese fonts, to have bold-ish effect by scaling up a little bit. Or simply per designer request. The most common use case among us is scaling up a number, like "Episode 99" on a label without using two TextViews.

**Comment by mightyfrog** [comment]
RelativeSizeSpan is very useful together with ColorSpan to keep layout

**Comment by mightyfrog** [comment]
Closed by mistake :(

**Comment by JakeWharton** [comment]
merged manually. thanks!

**Pull request closed without merging**
