### PR TITLE
Feature/security

### PR DESCRIPTION
**Pull request by VitaminPSG**
Encryption extension was added.

**Example:**
```
    val secretMessage = "Hello world"
    keyPairGeneratorOf(context, "MASTER_KEY").apply {
        val masterKey = genKeyPair()
        val cipher = cipherOf()
        val encryptedData = cipher.encrypt(secretMessage, masterKey.public)
        val decryptedData = cipher.decrypt(encryptedData, masterKey.private)
        val decryptedMessage = decryptedData.toString(Charset.defaultCharset())
        Assert.assertEquals(secretMessage, decryptedMessage)
    }
```

### CODE REVIEW

**Comment by JakeWharton** [comment]
This seems extremely specific, includes extensions for java.* types which are not supporting in this project, and has defaults which I'm not sure make sense for generally.

**Comment by VitaminPSG** [comment]
Thank you for your feedback.

I've replaced default values by builders. 
**Example:**
  
 ```
 val secretMessage = "Hello world"
 KeyPairGeneratorBuilder()
            .apply { algorithm = "AES" } // default is RSA
            .build("MASTER_KEY") // apply default KeyGenParameterSpec
            .apply {
                val masterKey = genKeyPair()
                val cipher = CipherBuilder().build() // create default Cipher
                val encryptedData = cipher.encrypt(secretMessage, masterKey.public)
                val decryptedData = cipher.decrypt(encryptedData, masterKey.private)
                val decryptedMessage = decryptedData.toString(Charset.defaultCharset())
                Assert.assertEquals(secretMessage, decryptedMessage)
            }
```


 ```
 val secretMessage = "Hello world"
 KeyPairGeneratorBuilder().build {
            val startDate = Calendar.getInstance()
            val endDate = Calendar.getInstance().apply { add(Calendar.YEAR, 20) }
            val spec = KeyPairGeneratorSpec.Builder(context)
                .setAlias(alias)
                .setSerialNumber(BigInteger.ONE)
                .setSubject(X500Principal("CN=$alias CA Certificate"))
                .setStartDate(startDate.time)
                .setEndDate(endDate.time)
                .build()
            it.initialize(spec)
        }
        .apply {
                val masterKey = genKeyPair()
                val cipher = CipherBuilder().build() // create default Cipher
                val encryptedData = cipher.encrypt(secretMessage, masterKey.public)
                val decryptedData = cipher.decrypt(encryptedData, masterKey.private)
                val decryptedMessage = decryptedData.toString(Charset.defaultCharset())
                Assert.assertEquals(secretMessage, decryptedMessage)
        }
```

 P.s. I guess that Android Keystore System is complicated and hope this changes will be helpful.

**Comment by bohsen** [comment]
Beautiful Work. You've boiled down encryption/decryption to less than 10 lines of code. This is how programming should always be 😁

**Comment by romainguy** [comment]
Those are extensions for non-Android types. This should be submitted to JetBrains for inclusion in the Kotlin std library.

**Pull request closed without merging**
