### PR TITLE
Add an extension for adding an animator listener by DSL

### PR DESCRIPTION
**Pull request by pokk**
It can add an animator listener by DSL as following below

```kotlin
animator.addAnimatorListener {
	onEnd { ... }
	onStart { ... }
	onCancel { ... }
	onRepeat { ... }
}
```

### CODE REVIEW

**Comment by JakeWharton** [comment]
We already have individual animation listeners and we don't want both. I don't see a lot of motivation to switch to this style since the likelihood that you're applying more than one callback is low and the overhead of doing so in the current style isn't terrible. Am I missing anything here?

**Comment by pokk** [comment]
Thank you for your feedback. I just though using DSL might be better.
And I agree with you that only for the DSL and plus a class is not a good idea. Is there a way to create the DSL without extra a class?

**Comment by hendraanggrian** [comment]
The thing about this is, if we start adding such feature, other listeners need to be converted to DSL as well. And there's a lot of them: `TextWatcher`, `OnGestureListener`, `OnScrollListener`, `OnItemSelectedListener`, `OnQueryTextListener`, `OnDrawerScrollListener`, etc.

**Comment by pokk** [comment]
@hendraanggrian 
Thank you for your suggestion. I think they will be a lot, too.

**Pull request closed without merging**
