### PR TITLE
Feature/log

### PR DESCRIPTION
**Pull request by VitaminPSG**
Logs usage:

- Equivalent of  `Log.i(javaClass.simpleName, message)`

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.test_activity)
        i("onCreate")
    }
```
```
   i {
            when (Build.VERSION.SDK_INT) {
                Build.VERSION_CODES.HONEYCOMB -> "HONEYCOMB"
                Build.VERSION_CODES.FROYO -> "FROYO"
                else -> "UNKNOWN"
            }
       }
```
```
i("Custom tag", "Log my version ${Build.VERSION.SDK_INT}")
```

### CODE REVIEW

**Comment by sourabhv** [comment]
I'd prefer it as 

```
info("I have a snake in my boot")
error("To infinity and ... StackOverflowException")
wtf("WTF! I still have a snake in my boot")
```

And the implementation could be

```
inline fun Any.info(message: String) = Log.i(javaClass.simpleName, message)
```

But I don't find this very useful

**Comment by romainguy** [comment]
The `isLoggable` aren't super useful since at that point you've already allocated all your strings.

**Comment by lukaspili** [comment]
Many kotlin developer create their own log() function, which calls `Timber.d` rather than `Log.d`.
Not sure it's such a great idea to pollute the IDE import window with an identical `log()` function that you don't want to use.
What about adding a prefix like `androidDebug()`, `androidError()`, etc?

**Comment by JakeWharton** [comment]
I don't think this provides a lot of added value. It's mostly code golfing character count. The lazy string one is interesting to potentially add as static extensions onto `Log` that check `isLoggable`, but we can't do that until https://youtrack.jetbrains.com/issue/KT-11968 is fixed so going to close for now.

**Pull request closed without merging**
