### PR TITLE
Add extensions for EditText.addTextChangedListener

### PR DESCRIPTION
**Pull request by sourabhv**

### CODE REVIEW

**Comment by sourabhv** [comment]
I signed it!

**Comment by MGaetan89** [comment]
Dup of #151?

**Comment by sourabhv** [comment]
@MGaetan89 Didn't see that one. My bad. 

#151 is still open. Any idea why?

**Comment by MGaetan89** [comment]
I guess because there are still some comments about the proposed implementation.

**Comment by davethomas11** [comment]
Newer #269 also has similar code

**Comment by JakeWharton** [comment]
Text watcher-based listeners have been merged in http://r.android.com/720364

**Pull request closed without merging**
