### PR TITLE
Kotlin commons and tests

### PR DESCRIPTION
**Pull request by gmjgh**
- Kotlin commons extensions for Long, String, Boolean and Any
- Tests for general/Commons
- API changes

### CODE REVIEW

**Comment by JakeWharton** [comment]
This library is focused on the Android APIs only. These should be requested upstream on the Kotlin standard library.

**Comment by gmjgh** [comment]
@JakeWharton does this apply to support libraries like design or cardview?

**Comment by JakeWharton** [comment]
No. Just the platform.

**Comment by gmjgh** [comment]
I signed it! (by the way) :)

**Pull request closed without merging**
