### PR TITLE
Add TextView listener extensions

### PR DESCRIPTION
**Pull request by zack-barakat**
This PR will add TextWatch implementation to pass actions instead of the whole interface. 
See Issue
#522

### CODE REVIEW

**Comment by zack-barakat** [comment]
In my local environment it actually passed the tests
but something wrong with firebase cloud test:

```
#!/bin/bash -eo pipefail
ftl-tests/setup.sh
GCLOUD_SERVICE_KEY env variable is empty. Exiting.
Exited with code 1
```

**Comment by chrnie233** [comment]
TextView add a TextWatcher  but never can remove, I do not think is good idea.

**Comment by zack-barakat** [comment]
@chrnie233  The return type for all the extension functions is the watcher, thus you can remove it by as with the function `removeTextChangedListener(watcher)`

```
val watcher = etEmail.afterTextChanged { etEmail.error = null }
txtReason.removeTextChangedListener(l)
```

**Comment by JakeWharton** [comment]
Text watcher-based listeners have been merged in http://r.android.com/720364

**Pull request closed without merging**
