### PR TITLE
Add boolean getter extensions to Cursor

### PR DESCRIPTION
**Pull request by DavidHamm**
there is a way to put boolean into the sqlite database like

`db.insert("table", null, contentValuesOf("booleanColumn" to true))`

or

`db.update("table", contentValuesOf("booleanColumn" to true), null, null)`

but there is no native function to get a boolean from a cursor.

therefore it would be nice to have some boolean getter extensions like

`cursor.getBoolean("booleanColumn")`

or

`cursor.getBooleanOrNull("booleanColumn")`

### CODE REVIEW

**Comment by DavidHamm** [comment]
I signed it!

**Comment by davethomas11** [comment]
See #201 and #266 for opinions on adding extensions to Cursor or other database related code.

**Comment by JakeWharton** [comment]
While this seems obvious, some DBs will store boolean values as T or F characters or literal values of "true"/"false" or "TRUE"/"FALSE". How you choose to store it is an implementation detail of your application and as such you can define these extensions directly in your project.

**Comment by JakeWharton** [comment]
No. Sound like it should be facilitated by the framework.

**Pull request closed without merging**
